name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install Google Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install Google Chrome dependencies
        run: sudo apt-get install -y unzip openjdk-8-jre-headless xvfb libxi6 libgconf-2-4
      - name: Install selenium
        run: sudo apt-get install -y python-selenium python3-selenium
      - name: Install Google Chrome driver
        run: sudo apt-get install chromium-chromedriver
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: pytest
